sudo: false
language: go

go:
  - 1.3
  - tip

services:
  - mysql

before_script:
  - mysql -e 'create database LocationTest;'

script: 
  - go get 
  - go get gopkg.in/check.v1 
  - go test ./...
  - go build
