version: '3'
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      - '.env'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 20

  weather:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - '.env'
    depends_on:
      - mysql